### ISSUE TITLE
Flappy test

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2157]
Error:
Promo::RegistrationStatsReportGeneratorTest#test_generates_report_for_daily_without_geo_information:
Faraday::ConnectionFailed: Failed to open TCP connection to 127.0.0.1:8194 (Connection refused - connect(2) for "127.0.0.1" port 8194)
    app/services/promo/registrations_stats_fetcher.rb:16:in `block in perform'
    app/services/promo/registrations_stats_fetcher.rb:14:in `each'
    app/services/promo/registrations_stats_fetcher.rb:14:in `perform'
    lib/error_handler_delegator.rb:13:in `block in method_missing'
    lib/error_handler.rb:12:in `handle_known_exceptions'
    lib/error_handler_delegator.rb:12:in `method_missing'
    app/services/promo/registration_stats_report_generator.rb:170:in `fetch_stats'
    app/services/promo/registration_stats_report_generator.rb:16:in `perform'
    lib/error_handler_delegator.rb:13:in `block in method_missing'
    lib/error_handler.rb:12:in `handle_known_exceptions'
    lib/error_handler_delegator.rb:12:in `method_missing'
    test/services/promo/registration_stats_report_generator_test.rb:247:in `block in <class:RegistrationStatsReportGeneratorTest>'
bin/rails test test/services/promo/registration_stats_report_generator_test.rb:235

**Comment by yachtcaptain23** [comment]
Fixed in https://github.com/brave-intl/publishers/commit/06bab553436a5044cb3e4ea4387cd441b4951a31#diff-19fff55be00be67540459512c0d1c45d
