### ISSUE TITLE
500 error on sign in for some users

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#2193]
```
2019-08-27T20:48:40.122117+00:00 app[web.2]: F, [2019-08-27T20:48:40.122014 #3] FATAL -- : 
2019-08-27T20:48:40.122176+00:00 app[web.2]: F, [2019-08-27T20:48:40.122113 #3] FATAL -- :  Faraday::ResourceNotFound (the server responded with status 404):
2019-08-27T20:48:40.122227+00:00 app[web.2]: F, [2019-08-27T20:48:40.122172 #3] FATAL -- : 
2019-08-27T20:48:40.122294+00:00 app[web.2]: F, [2019-08-27T20:48:40.122246 #3] FATAL -- :  app/services/base_api_client.rb:64:in `request'
2019-08-27T20:48:40.122296+00:00 app[web.2]:  app/services/base_api_client.rb:11:in `get'
2019-08-27T20:48:40.122297+00:00 app[web.2]:  app/services/uphold/models/address.rb:30:in `all'
2019-08-27T20:48:40.122299+00:00 app[web.2]:  lib/error_handler_delegator.rb:13:in `block in method_missing'
2019-08-27T20:48:40.122300+00:00 app[web.2]:  lib/error_handler.rb:12:in `handle_known_exceptions'
2019-08-27T20:48:40.122302+00:00 app[web.2]:  lib/error_handler_delegator.rb:12:in `method_missing'
2019-08-27T20:48:40.122303+00:00 app[web.2]:  app/jobs/create_uphold_channel_card_job.rb:61:in `get_address'
2019-08-27T20:48:40.122304+00:00 app[web.2]:  app/jobs/create_uphold_channel_card_job.rb:28:in `perform'
2019-08-27T20:48:40.122305+00:00 app[web.2]:  lib/error_handler_delegator.rb:13:in `block in method_missing'
2019-08-27T20:48:40.122306+00:00 app[web.2]:  lib/error_handler.rb:12:in `handle_known_exceptions'
2019-08-27T20:48:40.122307+00:00 app[web.2]:  lib/error_handler_delegator.rb:12:in `method_missing'
2019-08-27T20:48:40.122309+00:00 app[web.2]:  app/models/uphold_connection.rb:152:in `block in create_uphold_cards'
2019-08-27T20:48:40.122310+00:00 app[web.2]:  app/models/uphold_connection.rb:151:in `create_uphold_cards'
2019-08-27T20:48:40.122311+00:00 app[web.2]:  app/models/uphold_connection.rb:168:in `sync_from_uphold!'
2019-08-27T20:48:40.122312+00:00 app[web.2]:  app/controllers/publishers_controller.rb:218:in `home'
2019-08-27T20:48:40.122314+00:00 app[web.2]:  config/middlewares/http_header_middleware.rb:8:in `call'
```

**Comment by yachtcaptain23** [comment]
Fixed by https://github.com/brave-intl/publishers/pull/2200
