### ISSUE TITLE
TCP connection failures on start and reboot

### ISSUE THREAD

**Issue by yachtcaptain23** [brave-intl/publishers#3102]
We're seeing this error happening for some pods:

```
I, [2021-03-16T14:53:44.370004 #13]  INFO -- request: POST https://hooks.slack.com/services/xxxxxxxxx/xxxxxxxxxx/xxxxxxxxx
W, [2021-03-16T14:54:04.386967 #13]  WARN -- : Couldn't notify Slack in notify_boot.rb: Failed to open TCP connection to hooks.slack.com:443 (getaddrinfo: Temporary failure in name resolution)
sidekiq-7fc8979845-bwd5k publishers@2b3a5cc v608 started  -- falling back to logger
Eyeshade API: https://eyeshade.bsg.brave.com
PG::ConnectionBad: could not translate host name "xxxxxxxxxxxxx.compute-1.amazonaws.com" to address: Temporary failure in name resolution
/usr/local/bundle/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/usr/local/bundle/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/usr/local/bundle/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/connection_handling.rb:189:in `connection'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/railties/databases.rake:306:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/railties/databases.rake:302:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/railties/databases.rake:302:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/command.rb:48:in `invoke'
W, [2021-03-16T14:54:45.335091 #13]  WARN -- : Unable to record event with remote Sentry server (Raven::Error - execution expired):
/usr/local/bundle/gems/sentry-raven-2.11.3/lib/raven/transports/http.rb:34:in `rescue in send_event'
/usr/local/bundle/gems/sentry-raven-2.11.3/lib/raven/transports/http.rb:16:in `send_event'
/usr/local/bundle/gems/sentry-raven-2.11.3/lib/raven/client.rb:43:in `send_event'
/usr/local/bundle/gems/sentry-raven-2.11.3/lib/raven/instance.rb:81:in `send_event'
/usr/local/bundle/gems/sentry-raven-2.11.3/lib/raven/instance.rb:126:in `capture_type'
/usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `capture_exception'
/usr/local/bundle/gems/sentry-raven-2.11.3/lib/raven/integrations/rake.rb:9:in `display_error_message'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/application.rb:195:in `rescue in standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.3/lib/rake/application.rb:185:in `standard_exception_handling'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/command.rb:48:in `invoke'
W, [2021-03-16T14:54:45.335178 #13]  WARN -- : Failed to submit event: PG::ConnectionBad: could not translate host name "xxxxxxxxxxxxxx.compute-1.amazonaws.com" to address: Temporary failure in name resolution
```

The combination of being unreachable to Slack, Sentry, and AWS indicates there's likely something wrong on our end.

**Comment by yachtcaptain23** [comment]
Not reproducible. Closing.
